### ISSUE TITLE
Integrate SwiftLint

### ISSUE THREAD

**Issue by p4checo** [Mindera/Alicerce#124]
We should integrate SwiftLint in the project (Xcode build phase and CI), enforcing as many rules as possible from our [style guide](https://github.com/Mindera/swift-style-guide) 💪

**Comment by beloso** [comment]
I can pick this up ☝️

**Comment by p4checo** [comment]
Great! Not sure if it helps, but we're using a `.swiftlint.yml` on one of our current projects, that might be a good starting point:

```yaml
colon:
  apply_to_dictionaries: false
force_unwrapping: error
force_try: warning
disabled_rules:
    - closure_parameter_position
    - todo
    - unused_optional_binding
    - nesting
    - weak_delegate
    - large_tuple
    - type_name
    - generic_type_name
    - cyclomatic_complexity
    - identifier_name
opt_in_rules:
    - empty_count
    - closure_spacing
    - closure_end_indentation
    - weak_delegate
    - force_unwrapping
    - nimble_operator
    - object_literal
type_body_length:
  warning: 300
  error: 400
function_body_length:
  error: 150
number_separator:
  minimum_length: 5
empty_count: warning
excluded:
    - Carthage
    - Pods/
reporter: "xcode"
```

One important thing to note is that `SwiftLint` has a bug on the colon rule ([SwiftLint/#1901](https://github.com/realm/SwiftLint/issues/1901)), and we're still using `0.22.0` because of that 😓
